// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: class.sql

package database

import (
	"context"
)

const createClass = `-- name: CreateClass :one
INSERT INTO "class" ("grade", "section", "term_id", "program_id")
VALUES ($1, $2, $3, $4)
RETURNING id, grade, section, term_id, program_id
`

type CreateClassParams struct {
	Grade     int32
	Section   string
	TermID    int64
	ProgramID int64
}

func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) (Class, error) {
	row := q.db.QueryRowContext(ctx, createClass,
		arg.Grade,
		arg.Section,
		arg.TermID,
		arg.ProgramID,
	)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Grade,
		&i.Section,
		&i.TermID,
		&i.ProgramID,
	)
	return i, err
}

const deleteClass = `-- name: DeleteClass :exec
DELETE FROM "class"
WHERE "id" = $1
`

func (q *Queries) DeleteClass(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteClass, id)
	return err
}

const getClass = `-- name: GetClass :one
SELECT id, grade, section, term_id, program_id
FROM "class"
WHERE "id" = $1
LIMIT 1
`

func (q *Queries) GetClass(ctx context.Context, id int64) (Class, error) {
	row := q.db.QueryRowContext(ctx, getClass, id)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Grade,
		&i.Section,
		&i.TermID,
		&i.ProgramID,
	)
	return i, err
}

const listClasses = `-- name: ListClasses :many
SELECT id, grade, section, term_id, program_id
FROM "class"
`

func (q *Queries) ListClasses(ctx context.Context) ([]Class, error) {
	rows, err := q.db.QueryContext(ctx, listClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Class
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.Grade,
			&i.Section,
			&i.TermID,
			&i.ProgramID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClass = `-- name: UpdateClass :one
UPDATE "class"
SET "grade" = $2,
    "section" = $3,
    "term_id" = $4,
    "program_id" = $5
WHERE "id" = $1
RETURNING id, grade, section, term_id, program_id
`

type UpdateClassParams struct {
	ID        int64
	Grade     int32
	Section   string
	TermID    int64
	ProgramID int64
}

func (q *Queries) UpdateClass(ctx context.Context, arg UpdateClassParams) (Class, error) {
	row := q.db.QueryRowContext(ctx, updateClass,
		arg.ID,
		arg.Grade,
		arg.Section,
		arg.TermID,
		arg.ProgramID,
	)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Grade,
		&i.Section,
		&i.TermID,
		&i.ProgramID,
	)
	return i, err
}
