// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type Role string

const (
	RoleAdministrator Role = "administrator"
	RoleTeacher       Role = "teacher"
	RoleSecretary     Role = "secretary"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role
	Valid bool // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type Class struct {
	ID        int64
	Name      string
	TermID    int64
	ProgramID int64
}

type Lesson struct {
	ID        int64
	ClassID   int64
	TeacherID int64
	StartTime time.Time
	EndTime   time.Time
	FirstDate time.Time
	LastDate  time.Time
}

type Program struct {
	ID   int64
	Name string
}

type Subject struct {
	ID            int64
	Name          string
	ColorHexValue []byte
}

type Teacher struct {
	UserID            int64
	ContractStartDate time.Time
	ContractEndDate   time.Time
}

type TeacherSubjectAssignment struct {
	TermID    int64
	TeacherID int64
	SubjectID int64
}

type Term struct {
	ID        int64
	Name      string
	StartDate time.Time
	EndDate   time.Time
}

type User struct {
	ID           int64
	Username     string
	Name         string
	Surname      string
	PasswordHash []byte
	Role         Role
	CreatedAt    time.Time
	Deleted      bool
}

type Vacation struct {
	ID            int64
	Name          string
	StartDatetime time.Time
	EndDatetime   time.Time
}
