// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: program.sql

package database

import (
	"context"
)

const createProgram = `-- name: CreateProgram :one
INSERT INTO "program" ("name")
VALUES ($1)
RETURNING id, name
`

func (q *Queries) CreateProgram(ctx context.Context, name string) (Program, error) {
	row := q.db.QueryRowContext(ctx, createProgram, name)
	var i Program
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteProgram = `-- name: DeleteProgram :exec
DELETE FROM "program"
WHERE "id" = $1
`

func (q *Queries) DeleteProgram(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProgram, id)
	return err
}

const getProgram = `-- name: GetProgram :one
SELECT id, name
FROM "program"
WHERE "id" = $1
LIMIT 1
`

func (q *Queries) GetProgram(ctx context.Context, id int64) (Program, error) {
	row := q.db.QueryRowContext(ctx, getProgram, id)
	var i Program
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listPrograms = `-- name: ListPrograms :many
SELECT id, name
FROM "program"
`

func (q *Queries) ListPrograms(ctx context.Context) ([]Program, error) {
	rows, err := q.db.QueryContext(ctx, listPrograms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Program
	for rows.Next() {
		var i Program
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProgram = `-- name: UpdateProgram :one
UPDATE "program"
SET "name" = $2
WHERE "id" = $1
RETURNING id, name
`

type UpdateProgramParams struct {
	ID   int64
	Name string
}

func (q *Queries) UpdateProgram(ctx context.Context, arg UpdateProgramParams) (Program, error) {
	row := q.db.QueryRowContext(ctx, updateProgram, arg.ID, arg.Name)
	var i Program
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
