// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subject.sql

package database

import (
	"context"
)

const createSubject = `-- name: CreateSubject :one
INSERT INTO "subject" ("name", "color_hex_value")
VALUES ($1, $2)
RETURNING id, name, color_hex_value
`

type CreateSubjectParams struct {
	Name          string
	ColorHexValue []byte
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error) {
	row := q.db.QueryRowContext(ctx, createSubject, arg.Name, arg.ColorHexValue)
	var i Subject
	err := row.Scan(&i.ID, &i.Name, &i.ColorHexValue)
	return i, err
}

const deleteSubject = `-- name: DeleteSubject :exec
DELETE FROM "subject"
WHERE "id" = $1
`

func (q *Queries) DeleteSubject(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSubject, id)
	return err
}

const getSubject = `-- name: GetSubject :one
SELECT id, name, color_hex_value
FROM "subject"
WHERE "id" = $1
LIMIT 1
`

func (q *Queries) GetSubject(ctx context.Context, id int64) (Subject, error) {
	row := q.db.QueryRowContext(ctx, getSubject, id)
	var i Subject
	err := row.Scan(&i.ID, &i.Name, &i.ColorHexValue)
	return i, err
}

const listSubjects = `-- name: ListSubjects :many
SELECT id, name, color_hex_value
FROM "subject"
`

func (q *Queries) ListSubjects(ctx context.Context) ([]Subject, error) {
	rows, err := q.db.QueryContext(ctx, listSubjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subject
	for rows.Next() {
		var i Subject
		if err := rows.Scan(&i.ID, &i.Name, &i.ColorHexValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubject = `-- name: UpdateSubject :one
UPDATE "subject"
SET "name" = $2,
    "color_hex_value" = $3
WHERE "id" = $1
RETURNING id, name, color_hex_value
`

type UpdateSubjectParams struct {
	ID            int64
	Name          string
	ColorHexValue []byte
}

func (q *Queries) UpdateSubject(ctx context.Context, arg UpdateSubjectParams) (Subject, error) {
	row := q.db.QueryRowContext(ctx, updateSubject, arg.ID, arg.Name, arg.ColorHexValue)
	var i Subject
	err := row.Scan(&i.ID, &i.Name, &i.ColorHexValue)
	return i, err
}
