// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: term.sql

package database

import (
	"context"
	"time"
)

const createTerm = `-- name: CreateTerm :one
INSERT INTO "term" ("name", "start_date", "end_date")
VALUES ($1, $2, $3)
RETURNING id, name, start_date, end_date
`

type CreateTermParams struct {
	Name      string
	StartDate time.Time
	EndDate   time.Time
}

func (q *Queries) CreateTerm(ctx context.Context, arg CreateTermParams) (Term, error) {
	row := q.db.QueryRowContext(ctx, createTerm, arg.Name, arg.StartDate, arg.EndDate)
	var i Term
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const deleteTerm = `-- name: DeleteTerm :exec
DELETE FROM "term"
WHERE "id" = $1
`

func (q *Queries) DeleteTerm(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTerm, id)
	return err
}

const getTerm = `-- name: GetTerm :one
SELECT id, name, start_date, end_date
FROM "term"
WHERE "id" = $1
LIMIT 1
`

func (q *Queries) GetTerm(ctx context.Context, id int64) (Term, error) {
	row := q.db.QueryRowContext(ctx, getTerm, id)
	var i Term
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const listTerms = `-- name: ListTerms :many
SELECT id, name, start_date, end_date
FROM "term"
`

func (q *Queries) ListTerms(ctx context.Context) ([]Term, error) {
	rows, err := q.db.QueryContext(ctx, listTerms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Term
	for rows.Next() {
		var i Term
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTerm = `-- name: UpdateTerm :one
UPDATE "term"
SET "name" = $2,
    "start_date" = $3,
    "end_date" = $4
WHERE "id" = $1
RETURNING id, name, start_date, end_date
`

type UpdateTermParams struct {
	ID        int64
	Name      string
	StartDate time.Time
	EndDate   time.Time
}

func (q *Queries) UpdateTerm(ctx context.Context, arg UpdateTermParams) (Term, error) {
	row := q.db.QueryRowContext(ctx, updateTerm,
		arg.ID,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
	)
	var i Term
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}
