// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (
        "username",
        "name",
        "surname",
        "password_hash",
        "role",
        "created_at",
        "deleted"
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        CURRENT_TIMESTAMP,
        false
    )
RETURNING id, username, name, surname, password_hash, role, created_at, deleted
`

type CreateUserParams struct {
	Username     string
	Name         string
	Surname      string
	PasswordHash []byte
	Role         Role
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Name,
		arg.Surname,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Surname,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.Deleted,
	)
	return i, err
}

const deleteAuthor = `-- name: DeleteAuthor :exec
DELETE FROM "user"
WHERE "id" = $1
`

func (q *Queries) DeleteAuthor(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAuthor, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, username, name, surname, password_hash, role, created_at, deleted
FROM "user"
WHERE "id" = $1
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Surname,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.Deleted,
	)
	return i, err
}

const getUserWithUsername = `-- name: GetUserWithUsername :one
SELECT id, username, name, surname, password_hash, role, created_at, deleted
FROM "user"
WHERE "username" = $1
LIMIT 1
`

func (q *Queries) GetUserWithUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserWithUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Surname,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.Deleted,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, name, surname, password_hash, role, created_at, deleted
FROM "user"
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Name,
			&i.Surname,
			&i.PasswordHash,
			&i.Role,
			&i.CreatedAt,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE "user"
SET "username" = $2,
    "name" = $3,
    "surname" = $4,
    "password_hash" = $5,
    "role" = $6,
    "deleted" = $7
WHERE "id" = $1
RETURNING id, username, name, surname, password_hash, role, created_at, deleted
`

type UpdateUserParams struct {
	ID           int64
	Username     string
	Name         string
	Surname      string
	PasswordHash []byte
	Role         Role
	Deleted      bool
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Name,
		arg.Surname,
		arg.PasswordHash,
		arg.Role,
		arg.Deleted,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Surname,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.Deleted,
	)
	return i, err
}
