// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vacation.sql

package database

import (
	"context"
	"time"
)

const createVacation = `-- name: CreateVacation :one
INSERT INTO "vacation" ("name", "start_date", "end_date", "term_id")
VALUES ($1, $2, $3, $4)
RETURNING id, name, start_date, end_date, term_id
`

type CreateVacationParams struct {
	Name      string
	StartDate time.Time
	EndDate   time.Time
	TermID    int64
}

func (q *Queries) CreateVacation(ctx context.Context, arg CreateVacationParams) (Vacation, error) {
	row := q.db.QueryRowContext(ctx, createVacation,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.TermID,
	)
	var i Vacation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.TermID,
	)
	return i, err
}

const deleteVacation = `-- name: DeleteVacation :exec
DELETE FROM "vacation"
WHERE "id" = $1
`

func (q *Queries) DeleteVacation(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteVacation, id)
	return err
}

const getVacation = `-- name: GetVacation :one
SELECT id, name, start_date, end_date, term_id
FROM "vacation"
WHERE "id" = $1
LIMIT 1
`

func (q *Queries) GetVacation(ctx context.Context, id int64) (Vacation, error) {
	row := q.db.QueryRowContext(ctx, getVacation, id)
	var i Vacation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.TermID,
	)
	return i, err
}

const listVacationWithTermID = `-- name: ListVacationWithTermID :many
SELECT id, name, start_date, end_date, term_id
FROM "vacation"
WHERE "term_id" = $1
`

func (q *Queries) ListVacationWithTermID(ctx context.Context, termID int64) ([]Vacation, error) {
	rows, err := q.db.QueryContext(ctx, listVacationWithTermID, termID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vacation
	for rows.Next() {
		var i Vacation
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
			&i.TermID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVacations = `-- name: ListVacations :many
SELECT id, name, start_date, end_date, term_id
FROM "vacation"
`

func (q *Queries) ListVacations(ctx context.Context) ([]Vacation, error) {
	rows, err := q.db.QueryContext(ctx, listVacations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vacation
	for rows.Next() {
		var i Vacation
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
			&i.TermID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVacation = `-- name: UpdateVacation :one
UPDATE "vacation"
SET "name" = $2,
    "start_date" = $3,
    "end_date" = $4,
    "term_id" = $5
WHERE "id" = $1
RETURNING id, name, start_date, end_date, term_id
`

type UpdateVacationParams struct {
	ID        int64
	Name      string
	StartDate time.Time
	EndDate   time.Time
	TermID    int64
}

func (q *Queries) UpdateVacation(ctx context.Context, arg UpdateVacationParams) (Vacation, error) {
	row := q.db.QueryRowContext(ctx, updateVacation,
		arg.ID,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.TermID,
	)
	var i Vacation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.TermID,
	)
	return i, err
}
